spring:
  application:
    name: Config-Default


eureka:
  client:
    registerWithEureka : true
    fetchRegistry : true

  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
